INSERT INTO orders (id, customer_uid, order_date) VALUES (1, 1, '2018-05-30')
INSERT INTO orders (id, customer_uid, order_date) VALUES (2, 2, '2018-04-12')
INSERT INTO orders (id, customer_uid, order_date) VALUES (3, 5, '2018-04-14')
INSERT INTO orders (id, customer_uid, order_date) VALUES (4, 4, '2018-04-25')
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (1, 1, 4, 1, 30)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (2, 1, 3, 1, 50)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (3, 1, 5, 1, 200)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (4, 1, 1, 4, 5)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (5, 1, 2, 1, 60)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (6, 1, 6, 1, 20)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (7, 2, 3, 1, 45)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (8, 2, 6, 1, 20)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (9, 3, 1, 5, 5)
INSERT INTO order_items (id, order_id, product_uid, quantity, price) VALUES (10, 4, 2, 1, 60)
